server:
  port: 8080

spring:
  application:
    name: gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_app
    username: postgres
    password: 23528861
    initialization-mode: always
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      default-zone: http://discovery-sevice:8761/eureka/

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 14


