kind: Service
apiVersion: v1
metadata:
  name: gateway
  labels:
    name: gateway
spec:
  ports:
    - nodePort: 30160
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: avelibeyli6/guavapay-gateway:1.0
          ports:
            - containerPort: 8080
          env:   
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: name
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
